[package]
name = "hello_aptos_chain"
version = "1.0.0"
authors = []

[addresses]
hello_aptos_chain="_"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
